apiVersion: v1
kind: ConfigMap

metadata:
  name: event-gateway-config
  namespace: artifact-platform

data:
  KAFKA_BROKERS: "kafka-0.kafka-headless:9092"
  KAFKA_TOPIC: "harbor-events"
  PORT: "8080"