apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGNTCCBB2gAwIBAgIUL2DG4YhKJHipv/sj9gTsteVolXwwDQYJKoZIhvcNAQEL
    BQAwgakxCzAJBgNVBAYTAkVHMRYwFAYDVQQIDA1BZCBEYXFhaGxpeWFoMREwDwYD
    VQQHDAhNYW5zb3VyYTEnMCUGA1UECgweQ2xvdWQgTmF0aXZlIEFydGlmYWN0IFBs
    YXRmb3JtMRQwEgYDVQQLDAtEZXZlbG9wbWVudDEwMC4GA1UEAwwnQ2xvdWQgTmF0
    aXZlIEFydGlmYWN0IFBsYXRmb3JtIExvY2FsIENBMB4XDTI2MDgxNTEyMzQyN1oX
    DTM2MDgxMjEyMzQyN1owgakxCzAJBgNVBAYTAkVHMRYwFAYDVQQIDA1BZCBEYXFh
    aGxpeWFoMREwDwYDVQQHDAhNYW5zb3VyYTEnMCUGA1UECgweQ2xvdWQgTmF0aXZl
    IEFydGlmYWN0IFBsYXRmb3JtMRQwEgYDVQQLDAtEZXZlbG9wbWVudDEwMC4GA1UE
    AwwnQ2xvdWQgTmF0aXZlIEFydGlmYWN0IFBsYXRmb3JtIExvY2FsIENBMIICIjAN
    BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAuz3zf8NRumYUih/hWIHxFFKkaUBq
    UVd7MP28wXVPnN9TnbcBnXFqlbexaZJbyx29GMXe12zs7Gao6s6z7yOKT0PXA/Al
    UMOLVJdSwbXXiu7HHL6UAmpV2BHXQX4rRiy90YSt3ZZhakIVyIQTdLvSJ1pwu4Rp
    2aEQv4eLhP1j7ajsPRo5iR4vsttlQF5/ksGVTTOPEV63+QY2oa7h9otAtfJ6Tkwj
    6gJpq97ZWyt4L4U2/4cmrTUQ2voOsFXK8obtkaTyNEjzJ9JHrycU5tw/KSRFK3NB
    ghT62dpLGmevizADGvk/bfbcLCR3ozV4sN+sexzmhl7FikMvjb9MfZB8VdPPE43N
    C3mvOpGGgHW4Eeuf0F1FvchPdAVkOhVuWU3asmG+GCzqUdgVZCyG1/eHXjHQ7MCO
    B3QWn5Wb7MMvMobdHgjEFPxvLu1gMo4SfID6DbSVPVjmZpGR2ibsdbGi+F7J3JD1
    5IiNrBn7eNvD+K0CfelFAxqyTKqzWe4CItA4iemYxD/i2+8YDYBEkDqXn0Vczom3
    QQJ/laE+hoBvikAoYFoWC5956N0SrXgnzsMR+gTFVooKOfytmkIc1iZX7iWbNWrr
    chzAlMHZNfr0L20pJZeiRcLYkM7D7hsdlrDamMM8tJazOXm123D1ZRI+Fa3YgxIw
    7LZ1uy4wk6Qly4sCAwEAAaNTMFEwHQYDVR0OBBYEFBvozGk12eCv+hyTAvaLfxF/
    21aOMB8GA1UdIwQYMBaAFBvozGk12eCv+hyTAvaLfxF/21aOMA8GA1UdEwEB/wQF
    MAMBAf8wDQYJKoZIhvcNAQELBQADggIBAHVVPJcaMJp8nbdXMmdCOIXNL3THaBFd
    0fulOY3B9KTfA0GlfrV9/HaVjHFcbKEyPUUjM33Q07Hrp+pdkizknYpsURZ0rRM1
    NH61A0xzCz/Ikgw29cqgG47B0jwIylC154wlUklAJOihDWDRTUDG2RpaKEf2Tr2F
    thQ3ZKCS6olVZQHkXvgEVQ5O3T3lF3c3XPCccMu3uUwXY0c6eEOjcr3LYaCg8oyG
    e7dimUe8wvnr0Ts0XCQu3cbVmGgG/Mp29aE4ovo/xJJ/nLeYSiXlIldrmDe7JLXr
    mZcOikrlEtWsjDYcI4kLes2zCpETN0SdzK8enC32OoJWcOMObv02K1jODaHoovs8
    I9s5/qLHme5ZENx1aYjFXIPeBvu3wwzANdBdCxToTh4cYXTvIAIhVk37/4EXIAWW
    OEMhAnuSIp1pBcxBJzqMesjMar3S4cOXU6bGbLd/YigJkVjFmBRs0pdqXfKHy0PZ
    TWIuofBRXgGCIY4WBog+gHITsx59NNQVuEk1Akg4xkEhWtvlLC4nl8t/VCvD4gP2
    cxrlfmPdHP98Bj+v2SVuopDFRvWolRjDebs3vPhE4MDp7aFUgLiflhOOEKUkfK+V
    FV+B5BGgPbAL+2dS1WXzPl93IUe1uyE+rgNvQOEV9mtolHMwCdyvbk1425apzV7U
    zFVHoC132Doe
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: harbor-ca
  namespace: artifact-platform
