apiVersion: v1
kind: Service
metadata:
  name: image-verifier
  namespace: artifact-platform
spec:
  selector:
    app: image-verifier
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: metrics
      port: 2112
      targetPort: metrics