apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: artifact-platform-admission
webhooks:
  - name: admission.artifact-platform.local
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail

    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZoVENDQTIyZ0F3SUJBZ0lVS3Z4TE9NaWlLU2FSVGlCYWplanpoZ2N6ZXZZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRW5NQ1VHQTFVRUF3d2VZWEowYVdaaFkzUXRjR3hoZEdadmNtMHRZV1J0YVhOemFXOXVMV05oTVNjdwpKUVlEVlFRS0RCNURiRzkxWkNCT1lYUnBkbVVnUVhKMGFXWmhZM1FnVUd4aGRHWnZjbTB3SGhjTk1qWXdPREUyCk1EYzFOVFE1V2hjTk16WXdPREV6TURjMU5UUTVXakJTTVNjd0pRWURWUVFEREI1aGNuUnBabUZqZEMxd2JHRjAKWm05eWJTMWhaRzFwYzNOcGIyNHRZMkV4SnpBbEJnTlZCQW9NSGtOc2IzVmtJRTVoZEdsMlpTQkJjblJwWm1GagpkQ0JRYkdGMFptOXliVENDQWlJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dJUEFEQ0NBZ29DZ2dJQkFMRG1NaTJWCmRWV3Y0YjE4NllabkRtNzE3eGVVNS93SHVQb2lBYU9vWkd4OTBWc3dMMkZ0ejBrZWZLSmErTG9OWXJzL0dpYUoKWFZHNlhsNmx0VHYwUTRyZjM2aGx1Z2VHakhEWDh0NklwM2xVYWFlZVNDSkxmZXRHVFJiSCtyZWNvcU4rREpiMAozSy9mMkpBZmlBWk13UzR5cjRvRE9WRDJwTERJL0tiMlZ6U0pOM2xrVzk1bGpPbW9iaEFWVk10VDVwdHVsRDZyCkVlNlJ2Vi9aQzlKVjc4SWZHdG8zNHlkcjRndldLS1RlTGpHQ1NabGtlR0VrNkRFRGtCZUJMTmtLZXlocmRIYWUKK0xpRTdlLzBrd3p2cVBzZGhLTVBwVThlTnlXUHJuY1pXZzc3QWNhYTE5NTJHR29JSUdYVGtNS1N1N3grSXdFbwpZUkg0ajBJVnlZdEczM25PNitpRmUwRUtHZlNhbnJwMDY2dklueUVtZ25EdVFlUFhhZVpnMzZNOUdaemt1NENQCnM5YW8rUDBoQm5KdnFxNlZoOTFiR01PZkZMYk5jWExSL2R3WkZHZitpZlRGSjZjRk9qSEVxUGxDd1BWeEY1bE8KT3B0SjJSSXEzYVVENjZKZVdaMHJpUHpOWTMyd2FVVGduWFptZzdWSE44UHBHUjZZcm5KMk9wdElCbzYrTlQreQprSTdoa1dCdm4xTHB2VjlTbDB2VG5OenRvWUFkeGlLUjI1c0YxS3JRVTE5Y2M1VXVwdXltMk1JMEpMTUdXenJ6CkloLy93SzFIeXl0VVpBM0NpUTQ3TUQ2Rld6eXpuUXhrajdORlpvY29BUjdranFhWFpyN3pSL3FnTUZlNUxiVUYKMzRjbURIN1RzMGVTeWVCblVNTFN3NktEN0hpbTh3RDcrQ3ZQQWdNQkFBR2pVekJSTUIwR0ExVWREZ1FXQkJTVAp5ZGt6OC9OMWdzUTBSWE9pRUtlVC9rdzFFakFmQmdOVkhTTUVHREFXZ0JTVHlka3o4L04xZ3NRMFJYT2lFS2VUCi9rdzFFakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUFjU0duVVhQajgKVjgrOWxkREpIZXloaFVIck1iYXZqcjRJaFA0YmVzaEF2dFU5T0gyMm5nQjE3VUhQei9PdVlpSFFlYmVMRllwawpCQ01YUG9FWHowMFNkUzhtckROeDVwZlVKbWlkQmQ0MzRmdlBXV2NkMFpKbDBhbEJvVXRXeERURWhjRE1GYmhnCngrZnRBdUthYmhXc1lJTURvZXdTWjNKUGF3eFNERTNOVWptczVUMUFRQlZFdGNrVS9lcldaVlMwcG4wRGRJUWIKczBpQ2o1Nyt6WnNJQXV5UXJLZnBCSk9na2taZkErMEpnbkZzK1U0QUNpb2kxZ2Y0dkJiRUpmQ1hYTnlUYnh3ZwpIbk43bUlSOFpScUYvY3ZLNWliZzBYaXJwNmpob1A0Zkl5RTVjV2pDejFwYVA2SWd4a0JLbzJmaVkzU3ZacHFMCjlWRGRDdGg5SGJ6cjB6cUswaWEyL1Rzck1sUmFLVVczMFNRb1dLMnlxZzNDd0FsRzViaTc2SVlMNHdXZ09MaFkKamdZSzQ2TEJ2R0xUcy9UVTlrUURhOFJLQWIvY2R5TFBOZHZubktRYk5PdjBjdGJiNWREemo1azlOYWVJRGFXTApqWi84Vm5PZE0wZFcwdFJzVWNrcXRzbDlKbURsRUNCc3FkVzRwaGdNK1hEazRsQ2M4QmVFZVF0b05mN3pOd1IyCkFXUGZ0Mzc3NXVWbFpUY1FYSGJRazB3OEx4cnU1NXNOZ25ibFBVcjBkT2dVaVhtZEdoU1k4Q1U4cm9BaTl3ZFEKSVlzN2FRd3NtQlhwOERzcVFHT2tGVWtUcTZsclFkYlpidVNsVkRrSU5NTWlZNDVET0dOVWJ3bVdEaWFpSGhydgpuRHhzd21vU25pMjBRVjJWYVNmcXRMYzJsOXdVK1RhMnd3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: admission-webhook
        namespace: artifact-platform
        path: /validate
        port: 443

    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods

    namespaceSelector:
      matchLabels:
        artifact-platform-admission: enabled
