apiVersion: v1
kind: ConfigMap

metadata:
  name: metadata-worker-config
  namespace: artifact-platform

data:
  KAFKA_BROKERS: kafka-0.kafka-headless:9092
  KAFKA_TOPIC: harbor-events

  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: metadata
  DB_SSLMODE: disable

  METRICS_PORT: "2112"