apiVersion: v1
kind: Service
metadata:
  name: metadata-worker
  namespace: artifact-platform
spec:
  selector:
    app: metadata-worker
  ports:
    - name: metrics
      port: 2112
      targetPort: 2112
  type: ClusterIP
